### ISSUE TITLE
An example for stochastic collocation?

### ISSUE THREAD

**Issue by Stochastic-Adventure** [jherekhealy/AQFED.jl#2]
I read the 2nd Ed. of your book and am curious if a stochastic collocation fitting example could be shown here.

Thanks!

**Comment by jherekhealy** [comment]
There is example code in Matlab in the paper from Le Floc'h and Oosterlee. 
But I am almost finished with porting my own implementation to Julia (for the polynomial case).

**Comment by Stochastic-Adventure** [comment]
Thanks! After reading your book I'm sold on Julia and currently learning the language.

Looking forward to your implementation in this repo. But in the meantime, I'll try to find the Matlab code.

**Comment by jherekhealy** [comment]
I updated the github repo with some examples of stochastic collocation.

Best,
J.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
